/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cannonscheduler.ui;

import cannonscheduler.backend.Parser;
import cannonscheduler.backend.Request;
import cannonscheduler.ui.ScheduleDialog;
import cannonscheduler.ui.PasswordDialog;
import cannonscheduler.ui.RequestFormDialog;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author Travis
 */
public class CannonFrame extends javax.swing.JFrame {
    ArrayList<Request> requestList = new ArrayList<Request>();
    String fileLocation = "";
    
    /**
     * Creates new form CannonScheduleGUI
     */
    public CannonFrame() {
        initComponents();
    }
    
    public void updateRequestList(String filePath){
        int i;
        Parser parser = new Parser(filePath);
        if (parser != null){
            for(i=0;i<parser.getRequests().size();i++){ // For the length of the parsed array
                
                if (requestList.size() == 0) requestList.add(parser.getRequests().get(i)); // add to the list of requests
                
                boolean repeatedNameFlag = false;
                for(int j = 0; j < requestList.size(); j++) {
                    if(requestList.get(j).getGroupName().equals(parser.getRequests().get(i).getGroupName())){ // if the current list does not contain a request in the lst (avoids duplicates)
                        repeatedNameFlag = true;
                    }
                }
                
                if (!repeatedNameFlag) requestList.add(parser.getRequests().get(i)); // add to the list of requests
            }
        }
        for(Request r: requestList)
            System.out.println(r);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        makeNewRequestBtn = new javax.swing.JButton();
        seeCurrSchedBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        guiMenuBar = new javax.swing.JMenu();
        addCSV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 100, 100));
        jLabel1.setFont(new java.awt.Font("AR JULIAN", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cannon Scheduler");

        makeNewRequestBtn.setBackground(new java.awt.Color(240, 250, 80));
        makeNewRequestBtn.setFont(new java.awt.Font("Gabriola", 0, 60)); // NOI18N
        makeNewRequestBtn.setText("Make New Request");
        makeNewRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeNewRequestBtnActionPerformed(evt);
            }
        });

        seeCurrSchedBtn.setBackground(new java.awt.Color(240, 250, 80));
        seeCurrSchedBtn.setFont(new java.awt.Font("Gabriola", 0, 60)); // NOI18N
        seeCurrSchedBtn.setText("See Current Schedule");
        seeCurrSchedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeCurrSchedBtnActionPerformed(evt);
            }
        });

        jMenuBar1.setForeground(new java.awt.Color(100, 0, 0));

        guiMenuBar.setText("File");

        addCSV.setText("Add CSV File");
        addCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCSVActionPerformed(evt);
            }
        });
        guiMenuBar.add(addCSV);

        jMenuBar1.add(guiMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(makeNewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seeCurrSchedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seeCurrSchedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(makeNewRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makeNewRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeNewRequestBtnActionPerformed
        RequestFormDialog requestForm = new RequestFormDialog(this,true);
        requestForm.setArrayList(requestList);
        requestForm.setVisible(true);
        requestForm.setLocationRelativeTo(null);
        
        
        Request request = requestForm.getRequest();
        
        if (request != null) requestList.add(request);
        
//        for(Request r: requestList)
//            System.out.println(r);
    }//GEN-LAST:event_makeNewRequestBtnActionPerformed

    private void seeCurrSchedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeCurrSchedBtnActionPerformed
        ScheduleDialog scheduleDialog = new ScheduleDialog(this,true);
        scheduleDialog.setArrayList(requestList);
        scheduleDialog.updateTable();
        scheduleDialog.setVisible(true);
        scheduleDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_seeCurrSchedBtnActionPerformed

    private void addCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCSVActionPerformed
                                                       
        PasswordDialog passwordGUI = new PasswordDialog(this,true);
        passwordGUI.setVisible(true);
        passwordGUI.setLocationRelativeTo(null);
        
        
        boolean success = passwordGUI.getSuccess();
        
        if (success) {
            JFileChooser addFileChooser = new JFileChooser();
            int option = addFileChooser.showSaveDialog(this);
            if (option == JFileChooser.APPROVE_OPTION){ // save location of file
                fileLocation = addFileChooser.getSelectedFile().getPath();
                updateRequestList(fileLocation);
            } else if (option == JFileChooser.CANCEL_OPTION){
                addFileChooser.cancelSelection();
            }
        }
    }//GEN-LAST:event_addCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CannonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CannonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CannonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CannonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CannonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCSV;
    private javax.swing.JMenu guiMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton makeNewRequestBtn;
    private javax.swing.JButton seeCurrSchedBtn;
    // End of variables declaration//GEN-END:variables
}
