/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cannonscheduler.ui;

import cannonscheduler.backend.Request;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Sohail
 */
public class RequestFormDialog extends javax.swing.JDialog {

    ArrayList<Request> requestList;
    Request request;
    /**
     * Creates new form ReqFormGUI
     */
    public RequestFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }
    
    public void setArrayList(ArrayList<Request> requestList) {
        this.requestList = requestList;
    }
    
    public Request getRequest() {
        return request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        groupNameTF = new javax.swing.JTextField();
        numberOfPeopleTF = new javax.swing.JTextField();
        seniorityPointsTF = new javax.swing.JTextField();
        timeOfArrivalTF = new javax.swing.JTextField();
        hoursTF = new javax.swing.JTextField();
        minutesTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setForeground(new java.awt.Color(100, 0, 0));

        jLabel1.setFont(new java.awt.Font("AR JULIAN", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Request Form");

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel2.setText("Group Name");

        jLabel3.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel3.setText("Number Of People");

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel4.setText("Seniority Points");

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel5.setText("Arrival Time");

        jLabel6.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel6.setText("Length (Hours)");

        jLabel7.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        jLabel7.setText("Length (Minutes)");

        groupNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupNameTFActionPerformed(evt);
            }
        });

        numberOfPeopleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfPeopleTFActionPerformed(evt);
            }
        });
        numberOfPeopleTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberOfPeopleTFKeyTyped(evt);
            }
        });

        seniorityPointsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorityPointsTFActionPerformed(evt);
            }
        });
        seniorityPointsTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seniorityPointsTFKeyTyped(evt);
            }
        });

        timeOfArrivalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeOfArrivalTFActionPerformed(evt);
            }
        });

        hoursTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursTFActionPerformed(evt);
            }
        });

        minutesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesTFActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(240, 250, 80));
        jButton1.setFont(new java.awt.Font("Gabriola", 0, 60)); // NOI18N
        jButton1.setText("Save");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(240, 250, 80));
        jButton2.setFont(new java.awt.Font("Gabriola", 0, 60)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(groupNameTF)
                    .addComponent(numberOfPeopleTF)
                    .addComponent(seniorityPointsTF)
                    .addComponent(timeOfArrivalTF)
                    .addComponent(hoursTF)
                    .addComponent(minutesTF, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfPeopleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seniorityPointsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeOfArrivalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void groupNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupNameTFActionPerformed
        //JTextField myField = new JTextField("Default Text");
        //Group name
    }//GEN-LAST:event_groupNameTFActionPerformed

    private void numberOfPeopleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfPeopleTFActionPerformed
        // Number of people
    }//GEN-LAST:event_numberOfPeopleTFActionPerformed

    private void seniorityPointsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorityPointsTFActionPerformed
        // Seniority
    }//GEN-LAST:event_seniorityPointsTFActionPerformed

    private void timeOfArrivalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeOfArrivalTFActionPerformed
        // Arrival time
    }//GEN-LAST:event_timeOfArrivalTFActionPerformed

    private void hoursTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursTFActionPerformed
        // Lenght
    }//GEN-LAST:event_hoursTFActionPerformed

    private void minutesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesTFActionPerformed
        // Minutes
    }//GEN-LAST:event_minutesTFActionPerformed

    private void numberOfPeopleTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberOfPeopleTFKeyTyped
//        char c = evt.getKeyChar();
//        //final JFrame parent = new JFrame();
//        if(Character.toString(c).matches("[1-6]?")){
//            JTextField myField = new JTextField(c);
//        }
//        else {
//            JOptionPane.showMessageDialog(null,
//            "Only a single digit from 1 to 6 is allowed");
//        }
    }//GEN-LAST:event_numberOfPeopleTFKeyTyped

    private void seniorityPointsTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seniorityPointsTFKeyTyped
        char c = evt.getKeyChar();
        
        //final JFrame parent = new JFrame();
        if(Character.isDigit(c) ){
            
        }
    }//GEN-LAST:event_seniorityPointsTFKeyTyped


    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String groupName;
        
        int numberOfPeople;
        int seniorityPoints;
        int timeOfArrival;
        int hours;
        int minutes;
        
        for (Request request : requestList) {
            if (request.getGroupName().equals(groupNameTF.getText())) {
                JOptionPane.showMessageDialog(null, "Group with this name already exists");
                groupNameTF.setText("");
                return;
            }
        }
        
        if (groupNameTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Group Name can't be empty");
            return;
        }
        
        groupName = groupNameTF.getText();
        
        if (numberOfPeopleTF.getText().matches("[1-6]{1}"))
            numberOfPeople = Integer.parseInt(numberOfPeopleTF.getText());
        else {
            JOptionPane.showMessageDialog(null, "Only a single digit from 1 to 6 is allowed for Number of People");
            numberOfPeopleTF.setText("");
            return;
        }
        
        if (seniorityPointsTF.getText().matches("[1-5]{1}"))
            seniorityPoints = Integer.parseInt(seniorityPointsTF.getText());
        else {
            JOptionPane.showMessageDialog(null, "Only a single digit from 1 to 5 is allowed for Seniority Points");
            seniorityPointsTF.setText("");
            return;
        }
        
        if (timeOfArrivalTF.getText().matches("(0?[8-9]{1})|(1[0-6]{1})"))
            timeOfArrival = Integer.parseInt(timeOfArrivalTF.getText());
        else {
            JOptionPane.showMessageDialog(null, "Only values from 8 to 16 are allowed for Time of Arrivals");
            timeOfArrivalTF.setText("");
            return;
        }
        
        if (hoursTF.getText().matches("[0-3]{1}"))
            hours = Integer.parseInt(hoursTF.getText());
        else {
            JOptionPane.showMessageDialog(null, "Only a single digit from 0 to 3 is allowed for Hours");
            hoursTF.setText("");
            return;
        }
        
        if (minutesTF.getText().matches("(0?[0-9]{1})|([0-5]{1}[0-9]{1})"))
            minutes = Integer.parseInt(minutesTF.getText());
        else {
            JOptionPane.showMessageDialog(null, "Only values from 0 to 59 are allowed for Minutes");
            minutesTF.setText("");
            return;
        }
        
        float duration = (float) hours + (float) minutes / 60;
        if (duration > 3.0f) {
            
            JOptionPane.showMessageDialog(null, "Total Length cannot be greater than 3 hours");
            minutesTF.setText("0");
            return;
        }
        request = new Request(groupName, numberOfPeople, seniorityPoints, timeOfArrival, duration);
                
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RequestFormDialog dialog = new RequestFormDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField groupNameTF;
    private javax.swing.JTextField hoursTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField minutesTF;
    private javax.swing.JTextField numberOfPeopleTF;
    private javax.swing.JTextField seniorityPointsTF;
    private javax.swing.JTextField timeOfArrivalTF;
    // End of variables declaration//GEN-END:variables
}
